### ISSUE TITLE
Python port - maidenhead grid squares <--> lat, lon

### ISSUE THREAD

**Issue by tarxvftech** [tarxvftech/maidenhead#1]
I'd like a native Python implementation consisting of a function to convert a WGS84 [lat,lon] to a string maidenhead gridsquare, and another for the other direction.
This will require knowledge of C and Python alike. Don't do the tricks I did in the C version, which are largely because of the way C handles strings and memory.

Note the test cases in the existing .c file, and this documentation: http://w8bh.net/grid_squares.pdf
https://www.dxzone.com/grid-square-locator-system-explained/

This is a great issue for practicing and demonstrating TDD, so please also considering using python's unittests or another testing solution of your choice. Bonus points if the C implementation can use the same tests, somehow!

**Comment by Kabiirk** [comment]
This seems interesting ! I have experience in C++ and python, but haven't used both together, can you please assign this issue to me ?

**Comment by tarxvftech** [comment]
closed by #2! :D
